baseURL = 'https://shreyafadia.com'
languageCode = 'en-us'
title = 'Shreya Fadia'
theme = 'gruvhugo'
enableRobotsTXT = true   # render layouts/robots.txt (single source of truth)
[pagination]
  pagerSize = 10  # posts per page

[params.main]
  enabled      = true
  headerTitle  = 'Shreya Fadia'          # used in the site header
  name         = 'Shreya Fadia'          # used in meta author tag
  lang         = 'en'                    # used for <html lang="">
  description  = 'Shreya Fadia is a writer and editor based in North Carolina…'  # meta description for home page
  keywords     = 'Shreya Fadia, fiction, editor, writer'   # keywords for home page
  metaKeywords = 'author, fiction, editor'  # remove duplicates by using only one keywords tag
  img          = 'img/saf-photo.jpg'     # path in /static for og:image
  img_title    = 'portrait of Shreya Fadia' # alt/tooltip for photo
# add if we create a favicon
# icon         = 'img/favicon.svg'         # site favicon
  copyright    = '© 2025 Shreya Fadia. All rights reserved.'
  enableKatex  = false  # unless we need math rendering

# Add if Shreya creates socials
# [[params.social]]
#   name = 'linkedin'
#   url  = 'https://linkedin.com/in/shreya-fadia'

# [[params.social]]
#   name = 'github'
#   url  = 'https://github.com/shreyafadia'
