baseURL = 'https://shreyafadia.netlify.com'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'gruvhugo'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "post/"

  [[menu.main]]
    identifier = "wiki"
    name       = "Wiki"
    url        = "none"
