backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: master # optional, defaults to master
# backend:
#   name: git-gateway
#   local_backend: true
#   branch: main # Branch to update (optional; defaults to master)
local_backend:
  # when using a custom proxy server port
  url: http://localhost:8081/api/v1
media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files: 
    - label: "Site configuration "
      name: "site-config"
      file: "data/site.yml"
      editor:
        preview: false
      fields:
        - {label: "Main Image", name: "img", widget: "image", required: false }
        - {label: "Image Title", name: "img_title", widget: "string", required: false}
    - name: 'about'
      label: 'About (& homepage)'
      file: 'content/about.md'
      create: true
      fields:
        - { label: 'Menu',  name: 'menu', widget: 'hidden', default: "main" }
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Body', name: 'body', widget: 'markdown', hint: "Also shown as homepage content" }
        - { label: 'Hidden', name: 'draft', widget: 'boolean', default: false}
    - name: 'editing'
      label: 'Editing'
      file: 'content/Editing.md'
      create: true
      fields:
        - { label: 'Menu',  name: 'menu', widget: 'hidden', default: "main" }
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
        - { label: 'Hidden', name: 'draft', widget: 'boolean', default: true }
    - name: 'publications'
      label: 'Publications'
      file: 'content/publications.md'
      create: true
      fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
        - { label: 'Hidden',  name: 'draft', widget: 'boolean', default: false }
    - name: 'contact'
      label: 'Contact'
      file: 'content/contact.md'
      create: true
      fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
        - { label: 'Hidden',  name: 'draft', widget: 'boolean', default: false }